Added pickle support to the Python datetimetz, so far untested. Unfortunately, this broke the hash test in test_datetime.py, but the Python datetimetz.__hash__() has deeper problems than just that; e.g.,
>>> from datetime import *
>>> class ga(tzinfo):
...    def utcoffset(self, dt): return 1439
...
>>> dt = datetimetz(1, 1, 1, tzinfo=ga())
>>> hash(dt)
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "datetime.py", line 1530, in __hash__
    t = self - timedelta(minutes=tzoff)
  File "datetime.py", line 1483, in __sub__
    return supersub(other) # XXX should set tzinfo on result
  File "datetime.py", line 1318, in __sub__
    return self + -other
  File "datetime.py", line 1473, in __add__
    result = super(datetimetz, self).__add__(other)
  File "datetime.py", line 1302, in __add__
    self._checkOverflow(t.year)
  File "datetime.py", line 672, in _checkOverflow
    raise OverflowError("date +/-: result year %d not in %d..%d" %
OverflowError: date +/-: result year 0 not in 1..9999
>>>

So this mushrooms.