PyObject_HEAD already contains a semicolon, and MSVC can't tolerate putting another semicolon after it.  Getting rid of the semicolon clears up oodles of bogus errors.  Still doesn't compile on Windows, though:
datetime.c(226) : warning C4273: 'PyDateTime_Type' : inconsistent dll linkage.
dllexport assumed.
datetime.c(227) : error C2099: initializer is not a constant

plus lots of warnings, some of which look serious.