Fix the sometimes shortened traceback prints when an exception occurrs in a callback function.  Instead of printing the full traceback like this
  Exception: exception message

only the exception class name was printed in this way:

  Exception

The problem was that I was calling
  PyString_ConcatAndDel(&string, newpart)
with newpart not being a Python string.